/**
 * update-version.js — Tự động cập nhật phiên bản game từ git log
 *
 * Chạy: node update-version.js
 *
 * Sinh ra file src/version.js chứa:
 *   - GAME_VERSION — số commit (vd: v60)
 *   - COMMIT_HASH  — short hash (vd: 6d3ceb9)
 */

const { execSync } = require('node:child_process');
const { writeFileSync } = require('node:fs');
const { resolve } = require('node:path');

try {
  const commitCount = execSync('git rev-list --count HEAD', {
    cwd: __dirname,
    encoding: 'utf-8',
  }).trim();

  const commitHash = execSync('git rev-parse --short HEAD', {
    cwd: __dirname,
    encoding: 'utf-8',
  }).trim();

  const content = `// Auto-generated by update-version.js — chạy "node update-version.js" để cập nhật
export const GAME_VERSION = 'v${commitCount}';
export const COMMIT_HASH = '${commitHash}';
`;

  const outPath = resolve(__dirname, 'src', 'version.js');
  writeFileSync(outPath, content, 'utf-8');
  console.log(`✅  Đã cập nhật src/version.js → v${commitCount} (${commitHash})`);
} catch (err) {
  console.error('❌  Lỗi khi sinh version:', err.message);
  process.exit(1);
}
